.travis.yml
REQUIRE
src/ChebyshevJacobiPlan.jl
src/ChebyshevUltrasphericalPlan.jl
src/FastTransforms.jl
src/PaduaTransform.jl
src/cjt.jl
src/fftBigFloat.jl
src/specialfunctions.jl
src/toeplitzhankel.jl
test/fftBigFloattest.jl
test/runtests.jl

This starts supporting 0.6.  I've dropped 0.4 compatibility so that the `f.(x)` syntax can be used.  Are we OK with this change?  (I think `@compat` can restore 0.4 compatibility but I'm not sure it's worth it.)
the BigFloat FFT test fails for some reason: 
```julia
Testing BigFloat support of FFT and DCT methods
Test Failed
Expression: norm(ifft(fft(c)) - c) < 200 * (norm(c) * eps(BigFloat))
Evaluated: 3.290907383297889365567835493403282408529556851637210612211926363351574968498589e-13 < 2.841706296661406868731913357740366307573017126122182078005142968265071086475453e-74
ERROR: LoadError: LoadError: There was an error during testing
while loading /Users/solver/.julia/v0.6/FastTransforms/test/fftBigFloattest.jl, in expression starting on line 9
while loading …
```

WIP: Support 0.6

---

README.md
REQUIRE
docs/make.jl
docs/src/index.md
src/FastTransforms.jl
src/SphericalHarmonics/Butterfly.jl
src/SphericalHarmonics/SphericalHarmonics.jl
src/SphericalHarmonics/fastplan.jl
src/SphericalHarmonics/slowplan.jl
src/SphericalHarmonics/sphfunctions.jl
src/SphericalHarmonics/thinplan.jl
src/hierarchical.jl
src/toeplitzhankel.jl
test/basictests.jl
test/butterflytests.jl
test/runtests.jl
test/sphericalharmonictestfunctions.jl
test/sphericalharmonictests.jl
test/test_fastplan.jl
test/test_slowplan.jl
test/test_thinplan.jl

This adds Alpert & Rokhlin's Legendre-to-Chebyshev conversions via an adaptation of the Fast Multipole Method.
Using this [gist](https://gist.github.com/MikaelSlevinsky/09c43db2652d18a94483188a0099f373), the following error and timings plot compare and contrast the asymptotic, Toeplitz-dot-Hankel, and hierarchical methods. I propose that all methods be kept in the repository for future study.

Support Spherical Harmonics

---

src/SphericalHarmonics/SphericalHarmonics.jl
src/SphericalHarmonics/vectorfield.jl
test/sphericalharmonics/sphericalharmonictests.jl
test/sphericalharmonics/vectorfieldtests.jl

The basis is not smooth, but is rich enough to contain both the
spheroidal and toroidal components of a 2D vector field on the surface
of the sphere.
The Helmholtz decomposition would provide the pure spheroidal and
toroidal components.

Support 2D vector fields on the sphere

---

docs/src/index.md
src/ChebyshevJacobiPlan.jl
src/ChebyshevUltrasphericalPlan.jl
src/FastTransforms.jl
src/clenshawcurtis.jl
src/fejer.jl
src/specialfunctions.jl
test/basictests.jl

For the two strings `clenshawcurtis` and `fejer`, there are now three methods each:
`plan_*`, `*nodes`, `*weights`, where the Fejer methods are followed by a `1` or `2` to indicate the type.
This is a better interface because `*nodes` is more extensible: different Chebyshev moments may be added for new quadrature rules. In particular, this commit also adds `log` moments.

Update Interface for modified Chebyshev moment-based quadrature

---

src/fftBigFloat.jl
test/fftBigFloattests.jl

The BigFloat implementation of `idct` was not correct for complex-valued vectors it seems, only when they happened to be of complex type but real-valued.
I changed the implementation to one that seems to work and added a few tests for this case.
I also had to change the threshold for another test involving BigFloat fft's,  otherwise the test would fail in my setup.

Fix idct for complex-valued bigfloat vectors

---

src/fftBigFloat.jl
test/fftBigFloattests.jl

This pull request makes the generic FFT and DCT routines in FastTransforms available for all AbstractFloats. Some changes to the codeflow are described in https://github.com/MikaelSlevinsky/FastTransforms.jl/issues/62. An earlier issue was #34.
The code is written such that the more efficient plans of FFTW are still returned when T is one of the fftwNumber types. There is currently no check for this, which is dangerous. I suppose we could check on the type of the plan returned by `plan_fft`, but I'm not sure how to check which method of `fft` ends up being invoked. I would not be surprised if this pull request breaks things. The implementation remains a *lot* slower than FFTW of course, and it is also less accurate.
My goal was to make it work for `DoubleFloats.jl` types, such as …

Genericfft

---

src/fftBigFloat.jl
test/fftBigFloattests.jl

The previous generic FFT implementation would use generic FFT in various places even when FFTW was applicable. This is, of course, highly undesirable!
The changes here fix that, and also add tests to make sure that FFTW plans continue to be used for standard floating points. There is a runtime warning if generic fft's are used for Float32 or Float64 numbers.
The expected interface of AbstractFFTs is not entirely obvious. Some plans are only implemented for real numbers, some only for complex numbers, some plans are implemented in terms of other plans. As a result, when implementing plans for AbstractFloat we have to be careful in the typing of our implementation.

Make sure FFTW is maximally used

---

src/specialfunctions.jl
test/runtests.jl
test/specialfunctionstests.jl

`pochhammer `can now deal with arbitrary `::Number` without throwing unexpected errors.
I did this by adding a modified version of `gamma` function named `newgamma` which returns `Inf` at negative integers.
Added a test file.
Edit: following @dlfivefifty 's suggestion, I used `ogamma` which returns 0 at negative integers.

Make pochhammer more robust

---

.travis.yml
deps/build.jl
src/libfasttransforms.jl

This is a try at a cleaner buildscript and a cleaner Travis setup. All comments welcome.
Closes #84

Revamped buildscript

---

.cirrus.yml
Project.toml
README.md
examples/spinweighted.jl
src/FastTransforms.jl
src/libfasttransforms.jl
src/specialfunctions.jl
test/libfasttransformstests.jl

This adds support for spin-weighted spherical harmonics based on the minor release https://github.com/MikaelSlevinsky/FastTransforms/releases/tag/v0.3.0. The spin-weighted spherical harmonics are L^2 orthonormal, use a *complex* Fourier series for the longitudinal basis, have positive real phase, and only support complex coefficients. There is an example (spinweighted.jl) to get folks started and comfortable with the convention. Spin-0 === spherical harmonics with complex Fourier basis (Laurent in ApproxFun).
There are other goodies in that minor release that are added, e.g. SIMD Horner's rule and Clenshaw's algorithm. The computational kernels have a new API to be a little bit more flexible to new more exotic multivariate orthogonal polynomials that are isomorphic to the canonical …

Add spin-weighted spherical harmonics

---

Project.toml
deps/build.jl
src/FastTransforms.jl
src/libfasttransforms.jl
test/libfasttransformstests.jl

C controls `mpfr_t` memory, Julia controls `BigFloat` memory.
- Since `BigFloat`s have an extra field, `sizeof(BigFloat) == 40`, an array is passed as `mpfr_t **`, and implicitly the only datum in the second level of addressing is dereferenced by `[0]`.
- Since `BigFloat` is a mutable struct, there is no guarantee that each entry in
an `Array{BigFloat}` has a unique pointer. For example, looking at the `Limb`s,
```julia
julia> Id = Matrix{BigFloat}(I, 3, 3)
3×3 Array{BigFloat,2}:
1.0  0.0  0.0
0.0  1.0  0.0
0.0  0.0  1.0
julia> map(x->x.d, Id)
3×3 Array{Ptr{UInt64},2}:
Ptr{UInt64} @0x000000010f22f958  Ptr{UInt64} @0x000000010f22f918  Ptr{UInt64} @0x000000010f22f918
Ptr{UInt64} @0x000000010f22f918  Ptr{UInt64} @0x000000010f22f958  Ptr{UInt64} @0x000000010f22f918
Ptr{UInt64} …
```

cleanup C - Julia BigFloat interop

---

.travis.yml
Project.toml
README.md
deps/build.jl
src/clenshaw.jl

The new binaries support all Julia supported platforms from BinaryBuilder.jl
Adds "allowed_failures" testing on aarch64-linux (since they sometimes timeout).
Update build from source script, no longer need a specific GCC, can be built from Clang, provided one has libomp.

Feat libfasttransforms v0.3.3

---

examples/disk.jl
examples/sphere.jl
examples/triangle.jl

Since [Julia 1.4](https://github.com/JuliaLang/julia/blob/v1.4.2/NEWS.md), there is the very convenient `pkgdir` which many people overlook. Via code searches, I noticed that this repository uses some `dirname(dirname(pathof(FastTransforms)))` which is the same as `pkgdir(FastTransforms)`, so this PR proposes to replace that.

Use `pkgdir`

---

Project.toml
src/FastTransforms.jl
src/clenshaw.jl
src/libfasttransforms.jl

cuts down the load time by about 1/3 -- 1/2.
The calling sequences were probably dangerous too since an AbstractVector with AbstractColumnMajor layout could be conceived for which we don't point to the data.

remove ArrayLayouts

---

examples/nonlocaldiffusion.jl
src/libfasttransforms.jl

Alternate way to close #178 instead of #179.
Technically, all that #178 needs is to finish https://github.com/JuliaApproximation/FastTransforms.jl/commit/3ba4ee3b717598a7ed89fbe675e010c01c415bb9
but this PR goes further and allows unit strided array calls with `lmul!` and `ldiv!` (in-place transforms).  Later, the C library can be expanded to include more general strides.

allow views in *, \ and contiguous lmul! and ldiv!

---

src/PaduaTransform.jl
src/chebyshevtransform.jl
test/chebyshevtests.jl
test/clenshawtests.jl

* replaces non-breaking spaces with regular ones
* remove trailing white spaces
* add newlines at end of files
Only white spaces are changed in this PR, no code is affected

clean up whitespaces

---

Project.toml
src/libfasttransforms.jl

Instead of using a number of `const`s, we may use an `enum`. This doesn't change any behavior, but makes the types more readable.
```julia
julia> f = FastTransforms.plan_cheb2jac(rand(10), 0, 0);
julia> typeof(f)
FastTransforms.FTPlan{Float64, 1, FastTransforms.CHEB2JAC}
```
Should be non-breaking. I've checked locally that the tests for `ApproxFun` pass with this PR.

Enum of transforms

---

README.md

This package provides a simpler interface to the spherical harmonic transforms defined in `FastTransforms.jl`

Link to `FastSphericalHarmonics.jl` in Readme

---

Project.toml

FFTW v1.6 changes the type parameters of an r2rFFTWPlan, so this package breaks on that. This PR temporarily limits this package to older versions of FFTW while the issue is resolved.

Temporary upper bound on FFTW to < v1.6

---

Project.toml
src/chebyshevtransform.jl
test/chebyshevtests.jl

The main change in FFTW is that instead of the values of `kinds` being a type-parameter, it's stored as a struct field. This helps with type-stability.
I've renamed some of the variables in the tests, as this improved readability.
Test failures on Windows are seen on https://github.com/JuliaApproximation/FastTransforms.jl/pull/192 as well, so it's likely unrelated to this PR.

Make ChebyshevTransformPlan compatible with FFTW v1.6

---

src/FastTransforms.jl
test/toeplitzhankeltests.jl

This fixes #206 
We can change to using Toeplitz-dot-Hankel for large vectors later when the interface is refined

revert to libfasttransforms as default

---

examples/annulus.jl

Found as part of JuliaLang/julia#46372 - The reference parser allows the trailing semicolon after the block here, but JuliaSyntax.jl rejects it: Having a semicolon within [] would normally imply vcat. But having a semicolon followed by a `for` to make it into a comprehension? That's just... weird :-)

Fix weird syntax in annulus example

---

.github/workflows/ci.yml
Project.toml

FFTW v1.7 introduces certain changes to the type of `r2rFFTWPlan` (these are improvements over those introduced in v1.6, my bad for not incorporating it all in that version). Unfortunately, this change has led to breakages here. This PR limits the upper bound of FFTW to v1.6, and I'll submit another PR with the changes for v1.7 compatibility. 
It also removes the redundant test on v1.9, as v1 points to v1.9 now.

Limit FFTW compat to v1.6

---

.github/workflows/ci.yml
Project.toml
src/chebyshevtransform.jl
test/chebyshevtests.jl

This fixes breakages introduced by FFTW v1.7, and makes tests pass locally for me on Linux. It also simplifies types, and gets rid of hack-y workarounds for compatibility with FFTW v1.6.

Set FFTW lower compat bound to v1.7

---

.github/workflows/CIWindows.yml
.github/workflows/ci.yml
.github/workflows/docs.yml

Separating out the windows CI runs from the mac/linux ones will continue the latter even if the windows ones fail, and unlike continue-on-error, this won't report a success result status if tasks fail.
Once https://github.com/JuliaLang/julia/pull/50135 is backported, perhaps we should run the tests for WIndows only on Julia v1.9.2+

separate out windows CI tasks

---

Project.toml
src/PaduaTransform.jl
test/paduatests.jl

The main change is recognizing that we only need to evaluate the x coordinates once for each `k`, and the `y` coordinates for `k=n-1:n` and copy the values for the other `k`. This greatly reduces the number of transcendental function calls, and speeds up `paduapoints` considerably.
On master
```julia
julia> @btime FastTransforms.paduapoints(100);
160.437 μs (2 allocations: 80.55 KiB)
```
This PR
```julia
julia> @btime FastTransforms.paduapoints(100);
9.378 μs (2 allocations: 80.55 KiB)
```

Split y coordinate computation in `paduapoints`

---

src/chebyshevtransform.jl
test/chebyshevtests.jl

On master
```julia
julia> r = big(10)^400 .+ (0:1);
julia> chebyshevtransform(r)
2-element Vector{Float64}:
Inf
NaN
```
This PR fixes this.

Fix type-promotion in BigInt transforms

---

README.md

This shows whether the tests pass on the latest Julia nightly, and may be used as an early warning indicator of potential regressions. Clicking on the badge redirects one to the test failure report.

Add PkgEval badge to readme

---

src/chebyshevtransform.jl

This was left over from a type-stability hack, but isn't needed any more. In any case, the function `_fftKtype` isn't doing anything, and may be safely removed.

Remove unused leftover fixkind hack

---

src/chebyshevtransform.jl
test/chebyshevtests.jl

This fixes the inverse Chebyshev transform for immutable input vectors. The following works now:
```julia
julia> ichebyshevtransform(1.0:4.0)
4-element Vector{Float64}:
6.499813138042575
-4.05147160887461
1.808830921755324
-0.25717245092328955
```
This throws an error on master, as the input doesn't support in-place assignment.

Use a mutable copy of input if inplace scaling is required

---

src/chebyshevtransform.jl
src/toeplitzhankel.jl
src/toeplitzplans.jl

The `PermutedDimsArray` constructor is type-unstable if the permutation is not a compile-time constant, so it's best to avoid this if possible. In this PR, I have replaced the broadcast operations by explicit loops, which should be equivalent for `StridedArrays`. This reduces many extraneous allocations, and occasionally improves performance.
Example:
```julia
julia> @btime chebyshevtransform($(rand(100)));
51.582 μs (23 allocations: 1.75 KiB) # master
49.714 μs (6 allocations: 1.19 KiB) # PR
```
I'm unsure if infinite arrays are expected to be compatible with this package, in which case we may leave a generic fallback using `PermutedDimsArrays`.

Remove uses of PermutedDimsArray in pre and post-scaling
